version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: zglowa-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: zglowa-mailhog
      ports:
        - "1235:8025"

    redis:
      image: redis:alpine
      container_name: zglowa-redis

    postgres:
      image: postgres:11.1-alpine
      container_name: zglowa-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=admin123321
        - POSTGRES_DB=zglowa
      ports:
        - "1238:5432"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: zglowa-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: zglowa-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "1234:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: zglowa-php-fpm
      working_dir: /application
      volumes:
        - .:/application:cached
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      tty: true

    mongo:
      image: mongo
      container_name: mongodb

    localstack:
      container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
      image: localstack/localstack
      network_mode: bridge
      ports:
        - "4566:4566"
        - "4571:4571"
        - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
      environment:
        - SERVICES=${SERVICES- }
        - DEBUG=${DEBUG- }
        - DATA_DIR=${DATA_DIR- }
        - PORT_WEB_UI=${PORT_WEB_UI- }
        - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
        - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
        - DOCKER_HOST=unix:///var/run/docker.sock
        - HOST_TMP_FOLDER=${TMPDIR}
      volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
